version: '3.8'

services:

  postgres-fastapi:
    image: postgres:14.5
    expose:
      - 5432
    env_file:
      - ./.env

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - postgres-fastapi
